[package]
name = "agever"
version = "0.1.0"
edition = "2024"

[lib]
name = "agever"
crate-type = ["cdylib", "rlib"]

[[bin]]
# This can be whatever name makes sense for your project, but the rest of this tutorial assumes uniffi-bindgen.
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
modular-ac = { path = "../modular-ac" }
ark-std = "0.4"
ark-ff = "0.4.1"
base64 = "0.22"
ark-serialize = { version = "^0.4.1", default-features = false, features = [
    "derive",
] }
uniffi = { version = "0.31.1", features = [ "cli" ] }
serde = "1.0.228"
serde-binary = "0.5.0"
sha2 = "0.11.0"
chrono = "0.4.44"

[build-dependencies]
uniffi = { version = "0.31.1", features = [ "build" ] }
